---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: db
  labels:
    app: app
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      tier: db
  template:
    metadata:
      namespace: app
      name: db
      labels:
        app: app
        tier: db
    spec:
      containers:
        - image: mysql:8.0.31
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: test
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: cache
              mountPath: /tmp
          livenessProbe:
            tcpSocket:
              port: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
          startupProbe:
            tcpSocket:
              port: 3306
            failureThreshold: 10
            periodSeconds: 10
        - image: kimitsu/exsqus:test
          name: exsqus
          env:
            - name: MYSQL_HOST
              value: localhost
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
          volumeMounts:
            - name: cache
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8888
          startupProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: cache
          emptyDir: {}
