name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: write # semantic-releaseがrepositoryへのpush権限を要求する
      issues: read    # semantic-releaseがissueを検索できるように
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --pure-lockfile
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
      - run: git log
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            kimitsu/exsqus
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/login-action@v2
        with:
          username: kimitsu
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
