name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          change_path: "."
          bump_each_commit: true
      - run: |
          git tag ${{ steps.versioning.outputs.version_tag }}
          git push origin ${{ steps.versioning.outputs.version_tag }}
          git checkout refs/tags/${{ steps.versioning.outputs.version_tag }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            kimitsu/exsqus
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/login-action@v2
        with:
          username: kimitsu
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
