name: e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: ./script/e2e.sh
