name: e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: ./script/docker-e2e.sh
  kind:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.17.3
      - run: |
          ./script/kind-e2e.sh create
          ./script/kind-e2e.sh run
