name: e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - run: ./script/docker-e2e.sh
