name: lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.1
      - run: golangci-lint run
  hadolint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.1
      - run: hadolint Dockerfile
  shellcheck:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.1
      - run: shellcheck ./script/*.sh
