name: test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: write # semantic-releaseがrepositoryへのpush権限を要求する
      issues: read    # semantic-releaseがissueを検索できるように
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --pure-lockfile
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
      - run: git log
